# -*- coding: utf-8 -*-
"""semanticsearchwithfaiss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r76uQfUXIdMIW7cpQbu4ROGK2VsAZLa4
"""

!pip install faiss-cpu --no-cache

import faiss #Facebook AI Similarity Search
import numpy as np
from sentence_transformers import SentenceTransformer

""""all-MiniLM-L6-V2" is a pre-trained model which is known for being relatively fast and provides good sentence embeddings."""

model = SentenceTransformer('all-MiniLM-L6-v2')

documents = ["Artificial intelligence is transforming the way industries operate by automating complex tasks.",
            "Climate change poses a significant threat to global ecosystems and human societies.",
             "The rapid advancement of technology is reshaping education, creating new learning opportunities.",
             "Electric vehicles are gaining popularity due to their environmental benefits and lower operating costs.",
             "Healthcare systems around the world are integrating digital tools to improve patient care and management.",
            "Space exploration has led to numerous technological innovations, including satellite communication.",
             "Artificial intelligence is enhancing decision-making processes by analyzing vast amounts of data and providing actionable insights in real-time.",
             "The global economy is increasingly interconnected, with trade and investment flowing across borders.",
             "Renewable energy sources, such as solar and wind, are essential for reducing carbon emissions.",
             "Social media platforms have become a powerful tool for communication, marketing, and information sharing.",
             "Quantum computing has the potential to revolutionize industries by solving complex problems faster than traditional computers."]

document_embeddings = model.encode(documents)

index = faiss.IndexFlatL2(document_embeddings.shape[1])  # L2 distance
index.add(np.array(document_embeddings, dtype=np.float32))

query =  "How is artificial intelligence revolutionizing industries and what tasks are being automated?"
query_embedding = model.encode([query])

k = 3
distances, indices = index.search(np.array(query_embedding, dtype=np.float32), k)

print("Query:", query)
for i, idx in enumerate(indices[0]):
    print(f"Rank {i+1}: {documents[idx]} (Distance: {distances[0][i]:.4f})")

"""Which gives distances of top k ranks among all documents"""

